// Importa el tipo Metadata que permite definir información del documento
// como título, descripción, keywords, etc., para SEO y metadatos del proyecto.
import type { Metadata } from "next";

// Importa la fuente "Inter" desde Google Fonts usando la API optimizada de Next.js.
// Esto permite cargar la fuente de forma eficiente sin incluir archivos manualmente.
import { Inter } from "next/font/google";

// Importa los estilos globales del proyecto. Este archivo se aplica a toda la app.
import "./globals.css";

// Inicializa la fuente Inter con el subset "latin".
// Next.js gestionará la carga optimizada de esta fuente.
const inter = Inter({ subsets: ["latin"] });

// Objeto de metadatos utilizados por Next.js para configurar el <head> del documento.
// Estos datos se aplican por defecto a todas las páginas a menos que se sobrescriban.
export const metadata: Metadata = {
  title: "Create Next App",         // Título por defecto de la aplicación
  description: "Generated by create next app", // Descripción por defecto del sitio
};

// RootLayout es el layout principal de toda la aplicación.
// Next.js 13+ usa layouts para envolver todas las páginas y componentes.
// El parámetro `children` representa el contenido interno dinámico de cada página.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;  // Garantiza que `children` pueda ser cualquier elemento renderizable
}>) {
  return (
    // Define el idioma del documento HTML como inglés.
    <html lang="en">
      {/* 
        El body utiliza la clase generada por la fuente Inter.
        Esto aplica la tipografía a toda la aplicación de forma consistente.
      */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}